### ISSUE TITLE
Missing spec_coefficient File for Preprocessing

### ISSUE THREAD

**Issue by Factral** [youngchan-k/nespof#1]
Hello,

I really enjoyed reading your paper and was excited to run the code. However, I noticed that the `spec_coefficient` file is missing from the repository, which is required for preprocessing. Could you please provide this file or guide me on how to generate it?

https://github.com/youngchan-k/nespof/blob/6c3bb4054608e68d6b3bef821c1a038896544ccb/utils/data_proprecess_real.py#L97

I was also wondering if there is an equivalent spec_to_rgb function for preprocess synthethic from the .exr files or if this function also works for synthethic scenes.

Thank you!

**Comment by carlosh93** [comment]
Dear @youngchan-k Thank you for sharing your code. I have the same question as the one mentioned above and would greatly appreciate your assistance. Your guidance will help me reproduce the results and perform a fair comparison with my work.

Thank you in advance for your support!

**Comment by youngchan-k** [comment]
Thank you both for your interest! The _'spec_coefficient'_ has already been incorporated into other coefficients, including QE_w, PT_w, and FT_w, so it's no longer needed.

I've updated the code to work without using the coefficient. Please let me know if there are any other issues! :)

**Comment by youngchan-k** [comment]
@Factral For synthethic scene, you can preprocess the dataset in the same way as the real dataset. You can apply this function to synthetic dataset without dividing by the coefficient!

**Comment by Factral** [comment]
Thank you for your response and for updating the code.

I have a question regarding the data you shared. In the [Google Drive link](https://drive.google.com/drive/folders/1W7apuXPA3EkyUs8VgZgwdMpnc96aLXXJ) provided, I found only the polarimetric images, specifically the .exr files. However, in the code, to use the `spec_to_rgb` function there are references to the `undisort` folder and files with `-90` suffixes and `.png` extensions. There are no .png files in the shared data.

https://github.com/youngchan-k/nespof/blob/805f58b14431410b6483dcf1a07a0167f0dff0c8/utils/data_proprecess_real.py#L101

https://github.com/youngchan-k/nespof/blob/805f58b14431410b6483dcf1a07a0167f0dff0c8/utils/data_proprecess_real.py#L278


I am looking to obtain the ground truth RGB images for both the real and synthetic datasets. If possible, could you share the `undisort` folders so I can perform the preprocessing? Alternatively, if you already have the RGB images available, it would be very helpful if you could share them with me.

**Comment by youngchan-k** [comment]
In our paper, we describe capturing 21 wavelengths and 4 polarization angles to reconstruct the full-Stokes image for each wavelength. The dataset we have shared includes these reconstructed hyperspectral polarimetric images.

To generate ground truth RGB images, you should use the s0 component (the first channel) for each wavelength, as it represents the intensity. The `spec_to_rgb` function can be used for this.

**Comment by Factral** [comment]
Got it, thanks!

**Comment by carlosh93** [comment]
Many thanks for your help and prompt reply @youngchan-k !
